# Generated by Django 4.2.7 on 2023-11-16 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Univerisitas',
            new_name='Universitas',
        ),
    ]
