# Generated by Django 4.2.7 on 2023-11-21 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitas', '0002_rename_univerisitas_universitas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_cited',
            name='id',
        ),
        migrations.AddField(
            model_name='detail_cited',
            name='id_dosen',
            field=models.CharField(default='DC1', max_length=255, primary_key=True, serialize=False),
        ),
    ]
