# Generated by Django 4.2.7 on 2023-11-23 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universitas', '0004_alter_detail_cited_id_dosen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail_cited',
            name='id_dosen',
            field=models.CharField(default='DC', max_length=255, primary_key=True, serialize=False),
        ),
    ]
